# Updated to load the new partitions macro
load("//rules:defs.bzl", "esp32_binary", "esp32_image", "esp32_partitions")
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_binary(
    name = "hello",
    srcs = ["@arduino_esp32//:cores/esp32/main.cpp"],  # main must depend on the library containing setup and loop.
    visibility = ["//visibility:public"],
    deps = [
        ":hello_lib",
        "@arduino_esp32//:core_c_lib",
        "@arduino_esp32//:core_lib",
    ],
)

esp32_binary(
    name = "hello_esp32_xtensa",
    dep = ":hello",
)

cc_library(
    name = "hello_lib",
    srcs = ["hello.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "@arduino_esp32//:SPI",
    ],
)

esp32_image(
    name = "image",
    src = ":hello_esp32_xtensa",
)

esp32_partitions(
    name = "partitions",
    csv = "@arduino_esp32//:tools/partitions/min_spiffs.csv",
)

